# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(437, 386)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/windows-shutdown-button-icon-63541.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cB_after = QtWidgets.QCheckBox(self.groupBox)
        self.cB_after.setObjectName("cB_after")
        self.horizontalLayout.addWidget(self.cB_after)
        self.sB_hour = QtWidgets.QSpinBox(self.groupBox)
        self.sB_hour.setObjectName("sB_hour")
        self.horizontalLayout.addWidget(self.sB_hour)
        self.hour_lab = QtWidgets.QLabel(self.groupBox)
        self.hour_lab.setObjectName("hour_lab")
        self.horizontalLayout.addWidget(self.hour_lab)
        self.sB_minute = QtWidgets.QSpinBox(self.groupBox)
        self.sB_minute.setObjectName("sB_minute")
        self.horizontalLayout.addWidget(self.sB_minute)
        self.min_lab = QtWidgets.QLabel(self.groupBox)
        self.min_lab.setObjectName("min_lab")
        self.horizontalLayout.addWidget(self.min_lab)
        self.sB_second = QtWidgets.QSpinBox(self.groupBox)
        self.sB_second.setObjectName("sB_second")
        self.horizontalLayout.addWidget(self.sB_second)
        self.sec_lab = QtWidgets.QLabel(self.groupBox)
        self.sec_lab.setObjectName("sec_lab")
        self.horizontalLayout.addWidget(self.sec_lab)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cB_timestamp = QtWidgets.QCheckBox(self.groupBox)
        self.cB_timestamp.setObjectName("cB_timestamp")
        self.horizontalLayout_2.addWidget(self.cB_timestamp)
        self.attime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.attime.setObjectName("attime")
        self.horizontalLayout_2.addWidget(self.attime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cB_shutdown = QtWidgets.QCheckBox(self.groupBox_2)
        self.cB_shutdown.setObjectName("cB_shutdown")
        self.verticalLayout_4.addWidget(self.cB_shutdown)
        self.cB_restart = QtWidgets.QCheckBox(self.groupBox_2)
        self.cB_restart.setObjectName("cB_restart")
        self.verticalLayout_4.addWidget(self.cB_restart)
        self.cB_logout = QtWidgets.QCheckBox(self.groupBox_2)
        self.cB_logout.setObjectName("cB_logout")
        self.verticalLayout_4.addWidget(self.cB_logout)
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.lineE_option = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineE_option.setReadOnly(True)
        self.lineE_option.setObjectName("lineE_option")
        self.horizontalLayout_4.addWidget(self.lineE_option)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.lineE_seconds = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineE_seconds.setReadOnly(True)
        self.lineE_seconds.setObjectName("lineE_seconds")
        self.horizontalLayout_4.addWidget(self.lineE_seconds)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pB_start = QtWidgets.QPushButton(self.groupBox_2)
        self.pB_start.setObjectName("pB_start")
        self.horizontalLayout_3.addWidget(self.pB_start)
        self.pB_abort = QtWidgets.QPushButton(self.groupBox_2)
        self.pB_abort.setObjectName("pB_abort")
        self.horizontalLayout_3.addWidget(self.pB_abort)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.verticalLayout_3.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 437, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuInfo = QtWidgets.QMenu(self.menuBar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAppInfo = QtWidgets.QAction(MainWindow)
        self.actionAppInfo.setObjectName("actionAppInfo")
        self.actionAbouttheApp = QtWidgets.QAction(MainWindow)
        self.actionAbouttheApp.setObjectName("actionAbouttheApp")
        self.menuInfo.addAction(self.actionAppInfo)
        self.menuInfo.addAction(self.actionAbouttheApp)
        self.menuBar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ShutDown App 0.0"))
        self.groupBox.setTitle(_translate("MainWindow", "Select the time"))
        self.cB_after.setText(_translate("MainWindow", " after "))
        self.hour_lab.setText(_translate("MainWindow", "Hour"))
        self.min_lab.setText(_translate("MainWindow", "Minute"))
        self.sec_lab.setText(_translate("MainWindow", "Second"))
        self.label_4.setText(_translate("MainWindow", "Or"))
        self.cB_timestamp.setText(_translate("MainWindow", "at timestamp"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Select one option"))
        self.cB_shutdown.setText(_translate("MainWindow", "Shut down"))
        self.cB_restart.setText(_translate("MainWindow", "Restart"))
        self.cB_logout.setText(_translate("MainWindow", "Logout"))
        self.label.setText(_translate("MainWindow", "my computer in"))
        self.label_5.setText(_translate("MainWindow", "Seconds"))
        self.pB_start.setText(_translate("MainWindow", "Start"))
        self.pB_abort.setText(_translate("MainWindow", "Abort"))
        self.menuInfo.setTitle(_translate("MainWindow", "Help"))
        self.actionAppInfo.setText(_translate("MainWindow", "App Info"))
        self.actionAbouttheApp.setText(_translate("MainWindow", "About the App"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())

